version: '3.8'

services:
  db:
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: eugene
      POSTGRES_PASSWORD: eugene
      POSTGRES_DB: schooldb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/db_data
volumes:
  db_data: 
